---
# tasks file for Role_Stage
- name: install maven, java, git
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - maven
    - default-jdk
- name: create dir for project
  file:
    path: "{{ app_data}}"
    state: directory
- name: clone project
  git:
    repo: "{{ repository }}"
    dest: "{{ app_data }}"

