---
# tasks file for Role_Stage
- name: install maven, java, git
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - maven
    - default-jdk
- name: create dir for project
  file:
    path: "{{ app_data}}"
    state: directory
- name: clone project
  git:
    repo: "{{ repository }}"
    dest: "{{ app_data }}"
- name: create app
  shell:
    mvn package -f {{ app_data }}
- name: copy app to Web server
  synchronize:
    src: {{ app_data }}/target/hello-1.0.war
    dest: rsync://172.31.35.248/{{ dest_folder_tomcat8 }}
  delegate_to: WEB_01
