---
# tasks file for Role_DockerServer
- name: install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-pip
    - docker.io
- name: install docker
  shell:
    pip install docker
- name: Build docker image
  docker_image:
    name: gato_container
    path: /docker/
    state: build